#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo "start qiandao..."
nohup ${OPENSHIFT_DATA_DIR}bin/python2.7 ${OPENSHIFT_REPO_DIR}/diy/run.py > ${OPENSHIFT_DIY_LOG_DIR}server.log 2>&1 &
